// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUjgeXFU6jLVzK0W2vcnlBoH-3-cTOBRo',
    appId: '1:417582455838:web:616763c42ad01d13d1620f',
    messagingSenderId: '417582455838',
    projectId: 'e-sante-22d88',
    authDomain: 'e-sante-22d88.firebaseapp.com',
    storageBucket: 'e-sante-22d88.firebasestorage.app',
    measurementId: 'G-9HEKNTC6V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKCmExfPi9vkMjBiFdKKy7OtyifcpNL0Q',
    appId: '1:417582455838:android:23114d7e2e5760c5d1620f',
    messagingSenderId: '417582455838',
    projectId: 'e-sante-22d88',
    storageBucket: 'e-sante-22d88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3korXC67QUjQUDV_BjzrCc4_I_zqtY7o',
    appId: '1:417582455838:ios:99d55c39601cb97bd1620f',
    messagingSenderId: '417582455838',
    projectId: 'e-sante-22d88',
    storageBucket: 'e-sante-22d88.firebasestorage.app',
    iosBundleId: 'com.esante.esanteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3korXC67QUjQUDV_BjzrCc4_I_zqtY7o',
    appId: '1:417582455838:ios:99d55c39601cb97bd1620f',
    messagingSenderId: '417582455838',
    projectId: 'e-sante-22d88',
    storageBucket: 'e-sante-22d88.firebasestorage.app',
    iosBundleId: 'com.esante.esanteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUjgeXFU6jLVzK0W2vcnlBoH-3-cTOBRo',
    appId: '1:417582455838:web:0e76f4c714a7ea6ed1620f',
    messagingSenderId: '417582455838',
    projectId: 'e-sante-22d88',
    authDomain: 'e-sante-22d88.firebaseapp.com',
    storageBucket: 'e-sante-22d88.firebasestorage.app',
    measurementId: 'G-G8C2KHCPXC',
  );
}
